# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19JgNhahhKAVMUgu7F-ZD1SWOChYlXJN3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv("https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/FuelConsumptionCo2.csv")

df.head()

test_df = df[['MAKE','MODEL','ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB','CO2EMISSIONS']]
test_df.head(11)

plt.scatter(test_df.ENGINESIZE, test_df.CO2EMISSIONS,  color='Red')
plt.xlabel("Engine size")
plt.ylabel("Emission of CO2")
plt.show()

plt.scatter(test_df.FUELCONSUMPTION_CITY, test_df.CO2EMISSIONS,  color='blue')
plt.xlabel("Fuel consumption")
plt.ylabel("Emission of CO2")
plt.show()

msk = np.random.rand(len(df)) < 0.9
train = test_df[msk]
test = test_df[~msk]

plt.scatter(train.ENGINESIZE, train.CO2EMISSIONS,  color='red')
plt.xlabel("Engine size")
plt.ylabel("Emission of CO2")
plt.show()

plt.scatter(train.FUELCONSUMPTION_CITY, train.CO2EMISSIONS,  color='blue')
plt.xlabel("Fuel consumption")
plt.ylabel("Emission of CO2")
plt.show()

from sklearn import linear_model
regr = linear_model.LinearRegression()
x = np.array(train[['ENGINESIZE','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY']])
y = np.array(train[['CO2EMISSIONS']])
regr.fit (x, y)
print ('Coefficients are ', regr.coef_)
y_hat= regr.predict(test[['ENGINESIZE','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY']])
x = np.array(test[['ENGINESIZE','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY']])
y = np.array(test[['CO2EMISSIONS']])
print("Residual sum of squares is %.3f"% np.mean((y_hat - y) ** 2))
print('Variance score is %.3f' % regr.score(x, y))